### ISSUE TITLE
download_i18n.py missing

### ISSUE THREAD

**Issue by ulikoehler** [Khan/jenkins-jobs#1]
I've been reading about the `download_i18n.py` script [here](https://sites.google.com/a/khanacademy.org/forge/for-developers/i18n-development/i18n-system) and several times in the source code (e.g. [here](https://github.com/Khan/jenkins-tools/blob/e8eab519a4593cf5ee573070fc021cad21701638/update-translations.sh)). However, it does not seem to be present in any of the Khan repositories.

I need that file so we from the german translation team can review and verify the lint rules. We are currently reviewing lint errors and there seems to be a significant amount of false positives, see: http://kacheck.localgrid.de/lint.html

Any help in locating this file would be appreciated!

**Comment by tzjames** [comment]
Hi Uli,

Unfortunately much of that script right now is in a private repo.  We're open to making it public, but it's a bit of a complicated process. I have though made a gist of the file that handles the linting of poentries: https://gist.github.com/tzjames/d7325ab37ad807bc4c3e.  It definitely has some pretty complicated code in it, and any improvements/bug fixes that you find would be highly appreciated!

**Comment by ulikoehler** [comment]
Hi @tzjames !
Thank you very much for publishing the script! When I have some time to spare, I'll have a look at it!

**Comment by ulikoehler** [comment]
Here's a first issue and possible hotfix:
In our lint UI we have 54 occurrences of an error like this:
```
"" occurs 10 times in the english version but occurs 8 times in translated text
```
with different numbers.

I believe this error would be fixed by applying the following patch:
```
diff --git a/poentry_linter.py b/poentry_linter.py
index e748d35..251555b 100644
--- a/poentry_linter.py
+++ b/poentry_linter.py
@@ -136,6 +136,9 @@ def _assert_same(po_entry, regexp, ka_locale, munge_fn=None):
             for s in set(english_singular_counts.keys() +
                          english_plural_counts.keys() +
                          translated_counts.keys()):
+                # Hotfix for '"" occurs n times [...]' bug
+                if not s:
+                    continue
                 # Find the match from the regexp in which the number of times
                 # it occurred in the translated version differs from either the
                 # singular or plural.
```
Possibly there is a more specific underlying bug that lets empty strings occur in the set that is being iterated, but I'm not sure yet.

**Comment by tzjames** [comment]
Hi Uli,  Sorry for the delay in getting back to you.  We looked into this and the "" you are seeing on your lint reporting page is because you are not escaping the html output.  If you do that then you will see the tag that you are missing.
