### ISSUE TITLE
Invalid links in README.md

### ISSUE THREAD

**Issue by vsilverman** [Khan/jenkins-jobs#7]
[Related Repos](https://github.com/Khan/jenkins-jobs#related-repositories) section of the README.md file contains the following invalid github links:

[Jenkins setup](https://github.com/Khan/aws-config/) scripts

[Deploy system](https://github.com/Khan/internal-services/tree/master/buildmaster)

**Comment by benjaminjkraft** [comment]
These are valid links, they just aren't public repos.  Unfortunately we are unlikely to make them public at this time.
